apiVersion: v1
kind: Service
metadata:
  name: svc-techchallenge-node-sql
spec:
  type: NodePort
  selector:
    app: pod-techchallenge-sql
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 31400
